---
title: 
author: 
date: 
output:
  html_document:
    self_contained: no
---

Introduction
========================================================

Many applications on statistical data are aimed to produce models that "describe" and try to "predict" the relationship between a set of explicative variables and one (or more) dependent variable.

Also when the goal of an analysis is not focused on describing or predict phenomena (as, for example, in ANOVA applications or in $t$-test), often "behind the scenes" a statistical model is the "core" of the analysis.

The analytical philosophy in R is then strongly model-oriented, also when it seems not.

The main aim of this manual is then on discovering modeling capabilities of R language via practical applications, and on approaching the main functions used to develop Linear Models (LM) and Generalized Linear Models (GLM).  

The manual is then split in three main chapters: Linear Models, Generalized Linear Models, and Appendices.

The first two chapters initially show a theoretical introduction on the topic covered, and then several applied examples where many problems where addressed  by means of models.

The last chapter contains several paragraphs that introduce specific topics strictly linked to statistical modeling (with R), but that will require too much space to be broaden an deepen enough.

Before starting the exercises, we suggest to set the current R directory to the directory containing the example data files, using 

```{r,eval=FALSE}
setwd("current/directory")
```

where `current/directory` is the path for data directory.