---
output: html_document
---

```{r, options, echo=FALSE, results='hide', message=FALSE, warning=FALSE, purl=FALSE}
require(knitr)
opts_knit$set(root.dir = "../data")
require(ggplot2)
require(dplyr)
```


# Statistical Models with R

## Regression Analysis

Regression is the study of the change of the distribution of one variable, $y$, according to the value of another variable, $x$. Both continuous and discrete variables can be included in regression problems.

Formally, a relationship between $x$ and $y$ usually means that the expected value of $y$ is different for different values of $x$.

Regression model can be expressed in matrix form as:

$\vec{\mu} = E(\vec{y}) = \mathbf{X} \vec{\beta} + \vec{\varepsilon}$

where:

 - $\mathbf{X}$ is a $n \text{ x } (p+1)$ matrix, with all ones in the first columns, 
 - $\vec{\beta}$ is the vector of $\beta_0, \beta_1, \dots, \beta_p$,
 - $\vec{\varepsilon}$ is a **random** or **noise** component.

Models where response variable is a linear function of parameters are linear models.

Parameters values are usually estimated via maximum likelihood.

The main assumption of linear model is that the model is linear in the parameters. Other assumptions concern the error terms $\vec{\varepsilon}$ are:

 - $E(\varepsilon_{i}) = 0$ \hspace{1.7cm} ($i = 1, \dots, n$)
 - $\varepsilon_i \sim\; N(0,\,\sigma^2_\varepsilon)$ \hspace{1cm} ($i = 1, \dots, n$)
 - $Corr(\varepsilon_{i},\,\varepsilon_{i-j}) = 0$ \hspace{0.4cm} ($i = 1, \dots, n; 0 < j < i$)


The `lm` and `aov` functions are used in R to fit respectively linear regression and analysis of variance models.

The common interface to fit a statistical model in R is made of a call to the corresponding function with arguments `formula` and `data`.

Model formula general expression is $y \sim x_1 \pm x_2 \pm, \dots, \pm , x_k$.

Extensions to the above formula can be summarized as:


Expression                    | Description
----------------------------- | -------------
`y ~ x`                         | Simple regression
`y ~ 1 + x`                     | Explicit intercept
`y ~ -1 + x`                    | Through the origin
`y ~ x + x^2`                   | Quadratic regression
`y ~ x1 + x2 + x3`              | Multiple regression
`y ~ G + x1 + x2`               | Parallel regressions
`y ~ G / (x1 + x2)`             | Separate regressions
`sqrt(y) ~ x + x^2`             | Transformed
`y ~ G`                         | Single classification
`y ~ A + B`                     | Randomized block
`y ~ B + N * P`                 | Factorial in blocks
`y ~ x + B + N * P`             | with covariate 
`y ~  . -x1`                    | All variables except x1
`y ~  . + A:B`                  | Add interaction (update)
`Nitrogen ~ Times * (River/Site)` | More complex design

 
After fitting any statistical model, common R functions for inference are:

Expression                    | Description
----------------------------- | -------------
`coef(obj)`                    | regression coefficients
`resid(obj)`                   | residuals
`fitted(obj)`                  | fitted values
`summary(obj)`                 | analysis summary
`predict(obj, newdata = ndat)` | predict for newdata
`deviance(obj)`                | residual sum of squares

