---
title:
author:
date:
output:
  html_document:
    self_contained: no
---


```{r setup, echo=FALSE, message=FALSE, results='hide'}
require(tidyverse) 
require(knitr) 
options(width=80)
opts_chunk$set(list(dev = 'png', fig.cap='', fig.show='hold', dpi=100, fig.width=7, fig.height=7, fig.pos='H!'))#, fig.path="figures/lm-"))
opts_knit$set(root.dir="./data")
show_solution <- if (exists("show_solution_mk")){
  show_solution_mk
} else {
  FALSE
}


# ATTENZIONE: leggere nota dentro show-solution.R
```



## `summarise()`
Note: all the exercises of this section are based on the `flights` dataset.


```{r}
require(tidyverse)
require(nycflights13)
```


### Exercise 1
Calculate minimum, mean and maximum delay at arrival.

```{r, echo = show_solution, eval = show_solution}
flights %>% summarise(min_arr_delay = min(arr_delay, na.rm = T),
                      mean_arr_delay = mean(arr_delay, na.rm = T),
                      max_arr_delay = max(arr_delay, na.rm = T))
                      
```



### Exercise 2
Calculate minimum, mean and maximum delay at arrival for flights in January.

```{r, echo = show_solution, eval = show_solution}
flights %>% 
  filter(month == 1) %>%
  summarise(min_arr_delay = min(arr_delay, na.rm = T),
                      mean_arr_delay = mean(arr_delay, na.rm = T),
                      max_arr_delay = max(arr_delay, na.rm = T))
                      
```



### Exercise 3
Calculate the number of flights are contained in the dataset

```{r, echo = show_solution, eval = show_solution}
flights %>% 
  summarise(n_flights = n())
```

