---
title: "Summarise Data"
---

```{r options, include=FALSE, purl=FALSE}
options(width = 108)
```

```{r first, include=TRUE, purl=TRUE, message=FALSE}
require(dplyr)
require(qdata)
data(bank)
```


# `summarise()`

The last verb is `summarise()`, which collapses a data frame to a single row:

```{r}
# Compute the mean of balance variable of bank data frame
summarise(bank, mean_balance = mean(balance, na.rm = TRUE))
# Compute the minimum and the maximum value of balance of bank data frame
bank %>% summarise(max_balance = max(balance, na.rm = TRUE), min_balance = min(balance, na.rm = TRUE))
```


## Helper Functions for `summarise()`

* `first` returns the first value of a vector:

```{r}
bank %>% summarise(first(job))
```

* `last` returns the last value of a vector:

```{r}
bank %>% summarise(last(job)) 
```

* `nth` returns the nth value of a vector:

```{r}
bank %>% summarise(nth(job, 8))
```

* `n()` returns the number of values in a vector:

```{r}
bank %>% summarise(n())
```

* `n_distinct` returns the number of distinct values in a vector:

```{r}
bank %>% summarise(n_distinct(job))
bank %>% summarise(n_distinct(education))
```

