---
title: "Machine Learning with R"
---






# Introduction

This course will provide an overview of the main data mining techniques through the statistical software `R`. It is divided into five big sections:

1. **Basic data mining techniques**: simple descriptive techniques to analyze single variables;
2. **Dimensionality reduction**: whose aim is at showing some methods to reduce the number of variables contained in the data by keeping almost the same information;
3. **Clustering**: when the objective of the analysis is to divide observations into groups, created on the basis of the variables at our disposal;
4. **Classification**: when the objective of the analysis is to correctly assign a new observation to a value of a categorical response variable, through a proper statistical model estimated from the data;
5. **Prediction**: when the objective of the analysis is to predict the numeric value of a response variable in a new observation, through a proper statistical model estimated from the data.

Several `R` packages, besides the base `R` distribution, will be used in this course: `boot`, `ca`, `caret`, `clusterSim`, `dplyr`, `e1071`, `ellipse`, `fBasics`, `GGally`, `ggplot2`, `glmnet`, `hdm`, `Hmisc`, `HSAUR2`, `ISLR`, `kohonen`, `lattice`, `leaps`, `MASS`, `mclust`, `MCMCpack`, `mice`, `MSQC`, `mvnormtest`, `mvtnorm`, `party`, `pls`, `pROC`, `psych`, `reshape2`, `rgl`, `rpart`, `rpart.plot`, `smacof`, `tree`.  

Please, install of them before starting.


# Datasets Used in the Examples of This Course

Let us load the datasets which will be used in the examples of this course. They are loaded from the packages `qdata`, `HSAUR2`, `smacof`, `ISLR` and `rpart`:


```r
## Remove all objects in the R environment
rm(list = ls())

## qdata package
require(qdata)

## qdata data frames used in this course
course_qdata_df <- c("banknotes","bimetal1","bostonhousing","druguse","forbes94","german","life","mds",
                     "uscompanies","uscrime","utilities","volcano3d","wea","wwiileaders","wines")

## Load qdata data frames used in this course
data(list = course_qdata_df)

## Load other data frames used in this course
data(skulls, package = "HSAUR2")
data(bread, package = "smacof")
data(Auto, Carseats, Default, Smarket, package = "ISLR")
data(cu.summary, kyphosis, package = "rpart")
```

The following datasets are used in the examples of this course.


## `Auto`
This dataset, included in the `R` package `HSLR`, deals with 392 vehicles on which 9 variables are measured (Games, G., Witten, D., Hastie, T., and Tibshirani, R., *An Introduction to Statistical Learning with applications in `R`*, [www.statlearning.com](www.statlearning.com), Springer-Verlag, 2013).


```r
str(Auto)
```

```
## 'data.frame':	392 obs. of  9 variables:
##  $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
##  $ cylinders   : num  8 8 8 8 8 8 8 8 8 8 ...
##  $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
##  $ horsepower  : num  130 165 150 150 140 198 220 215 225 190 ...
##  $ weight      : num  3504 3693 3436 3433 3449 ...
##  $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
##  $ year        : num  70 70 70 70 70 70 70 70 70 70 ...
##  $ origin      : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ name        : Factor w/ 304 levels "amc ambassador brougham",..: 49 36 231 14 161 141 54 223 241 2 ...
```

For further details, see the help page of the data: `?ISLR::Auto`


## `banknotes`
This dataset deals with 200 old Swiss 1,000-franc banknotes classified by dimensions (6 numerical characteristics) and type (genuine/counterfeit) (see Härdle and Simar, *Applied Multivariate Statistical Analysis*, 3rd ed., Springer, 2012).


```r
str(banknotes)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	200 obs. of  7 variables:
##  $ length  : num  215 215 215 215 215 ...
##  $ left    : num  131 130 130 130 130 ...
##  $ right   : num  131 130 130 130 130 ...
##  $ bottom  : num  9 8.1 8.7 7.5 10.4 9 7.9 7.2 8.2 9.2 ...
##  $ top     : num  9.7 9.5 9.6 10.4 7.7 10.1 9.6 10.7 11 10 ...
##  $ diagonal: num  141 142 142 142 142 ...
##  $ type    : Factor w/ 2 levels "counterfeit",..: 2 2 2 2 2 2 2 2 2 2 ...
```

For further details, see the help page of the data: `?banknotes`


## `bimetal1`
This dataset, derived from the dataset with the same name included in the `R` package `MSQC`, deals with 28 metal strips on which 5 numerical variables are measured (defelection, curvature, resistivity Hardness, low side Hardness, high side).


```r
str(bimetal1)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	28 obs. of  5 variables:
##  $ deflection        : num  20.8 20.9 21.1 20.4 21.3 ...
##  $ curvature         : num  39.8 39.9 40.1 39.8 40.3 ...
##  $ resistivity       : num  15 14.9 15.6 14.7 15.6 ...
##  $ Hardness.low.side : num  21.9 22 22.1 21.5 22.6 ...
##  $ Hardness.high.side: num  25.9 26 26.1 25.7 26.2 ...
```

For further details, see the help page of the data: `?bimetal1`


## `bostonhousing`
This dataset deals with 506 houses in Boston classified by 13 numerical characteristics (age, tax, etc.) and one categorical characteristic (chas).


```r
str(bostonhousing)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	506 obs. of  14 variables:
##  $ crim   : num  0.00632 0.02731 0.02729 0.03237 0.06905 ...
##  $ zn     : num  18 0 0 0 0 0 12.5 12.5 12.5 12.5 ...
##  $ indus  : num  2.31 7.07 7.07 2.18 2.18 2.18 7.87 7.87 7.87 7.87 ...
##  $ chas   : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 1 1 ...
##  $ nox    : num  0.538 0.469 0.469 0.458 0.458 0.458 0.524 0.524 0.524 0.524 ...
##  $ rm     : num  6.58 6.42 7.18 7 7.15 ...
##  $ age    : num  65.2 78.9 61.1 45.8 54.2 58.7 66.6 96.1 100 85.9 ...
##  $ dis    : num  4.09 4.97 4.97 6.06 6.06 ...
##  $ rad    : num  1 2 2 3 3 3 5 5 5 5 ...
##  $ tax    : num  296 242 242 222 222 222 311 311 311 311 ...
##  $ ptratio: num  15.3 17.8 17.8 18.7 18.7 18.7 15.2 15.2 15.2 15.2 ...
##  $ b      : num  397 397 393 395 397 ...
##  $ lstat  : num  4.98 9.14 4.03 2.94 5.33 ...
##  $ medv   : num  24 21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 ...
```

For further details, see the help page of the data: `?bostonhousing`


## `bread`
The data, included in the `R` package `smacof`, contains 8 distance matrices carried out by 8 raters, based on ratings of 10 breads on 11 different attributes. Note that the bread samples are pairwise replications: each of the 5 different breads, which have a different salt content, was presented twice for rating. The attributes are bread odor, yeast odor, off-flavor, color, moisture, dough, salt taste, sweet taste, yeast taste, other taste, and total.


```r
str(bread)
```

```
## List of 8
##  $ 1:Class 'dist'  atomic [1:45] 3.32 6.86 6.78 5.29 7.62 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[1L]], method = "minkowski")
##  $ 2:Class 'dist'  atomic [1:45] 3.16 9.8 10.44 9.49 6.24 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[2L]], method = "minkowski")
##  $ 3:Class 'dist'  atomic [1:45] 4.9 6 6.4 8 6.48 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[3L]], method = "minkowski")
##  $ 4:Class 'dist'  atomic [1:45] 3.16 9.43 7.62 7.94 8.12 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[4L]], method = "minkowski")
##  $ 5:Class 'dist'  atomic [1:45] 3 8.06 6.63 7.35 5.92 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[5L]], method = "minkowski")
##  $ 6:Class 'dist'  atomic [1:45] 3.61 5.66 8.19 7 7 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[6L]], method = "minkowski")
##  $ 7:Class 'dist'  atomic [1:45] 6 9.38 8.31 6.63 10.1 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[7L]], method = "minkowski")
##  $ 8:Class 'dist'  atomic [1:45] 3.46 10.77 11.96 9.54 11.18 ...
##   .. ..- attr(*, "Size")= int 10
##   .. ..- attr(*, "Labels")= chr [1:10] "Bread1.1" "Bread1.2" "Bread2.1" "Bread2.2" ...
##   .. ..- attr(*, "Diag")= logi FALSE
##   .. ..- attr(*, "Upper")= logi FALSE
##   .. ..- attr(*, "method")= chr "minkowski"
##   .. ..- attr(*, "p")= num 2
##   .. ..- attr(*, "call")= language FUN(x = X[[8L]], method = "minkowski")
```

For further details, see the help page of the data: `?smacof::bread`


## `Carseats`
This dataset, included in the `R` package `ISLR`, deals with sales of child car seats at 400 different stores (see James, G., Witten, D., Hastie, T., and Tibshirani, R., *An Introduction to Statistical Learning with applications in `R`*, Springer, 2013).


```r
str(Carseats)
```

```
## 'data.frame':	400 obs. of  11 variables:
##  $ Sales      : num  9.5 11.22 10.06 7.4 4.15 ...
##  $ CompPrice  : num  138 111 113 117 141 124 115 136 132 132 ...
##  $ Income     : num  73 48 35 100 64 113 105 81 110 113 ...
##  $ Advertising: num  11 16 10 4 3 13 0 15 0 0 ...
##  $ Population : num  276 260 269 466 340 501 45 425 108 131 ...
##  $ Price      : num  120 83 80 97 128 72 108 120 124 124 ...
##  $ ShelveLoc  : Factor w/ 3 levels "Bad","Good","Medium": 1 2 3 3 1 1 3 2 3 3 ...
##  $ Age        : num  42 65 59 55 38 78 71 67 76 76 ...
##  $ Education  : num  17 10 12 14 13 16 15 10 10 17 ...
##  $ Urban      : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 1 2 2 1 1 ...
##  $ US         : Factor w/ 2 levels "No","Yes": 2 2 2 2 1 2 1 2 1 2 ...
```

For further details, see the help page of the data: `?ISLR::Carseats`


## `cu.summary`
This dataset, included in the `R` package `rpart`, deals with makes of cars taken from the April, 1990 issue of *Consumer Reports*. It has 117 rows and 5 columns.


```r
str(cu.summary)
```

```
## 'data.frame':	117 obs. of  5 variables:
##  $ Price      : num  11950 6851 6995 8895 7402 ...
##  $ Country    : Factor w/ 10 levels "Brazil","England",..: 5 5 10 10 10 7 5 6 6 7 ...
##  $ Reliability: Ord.factor w/ 5 levels "Much worse"<"worse"<..: 5 NA 1 4 2 4 NA 5 5 2 ...
##  $ Mileage    : num  NA NA NA 33 33 37 NA NA 32 NA ...
##  $ Type       : Factor w/ 6 levels "Compact","Large",..: 4 4 4 4 4 4 4 4 4 4 ...
```

For further details, see the help page of the data: `?part::cu.summary`


## `Default`
This dataset, included in the `R` package `ISLR`, deals with 10,000 customers with the aim to predict which customers will default on their credit card debt (see James, G., Witten, D., Hastie, T., and Tibshirani, R., *An Introduction to Statistical Learning with applications in `R`*, Springer, 2013).


```r
str(Default)
```

```
## 'data.frame':	10000 obs. of  4 variables:
##  $ default: Factor w/ 2 levels "No","Yes": 1 1 1 1 1 1 1 1 1 1 ...
##  $ student: Factor w/ 2 levels "No","Yes": 1 2 1 1 1 2 1 2 1 1 ...
##  $ balance: num  730 817 1074 529 786 ...
##  $ income : num  44362 12106 31767 35704 38463 ...
```

For further details, see the help page of the data: `?ISLR::Default`


## `druguse`
The data contains the correlation matrix among rates (recorded on a 5-point scale) for a sample of 1,634 students in the seventh to ninth grades in 11 schools in the greater metropolitan area of Los Angeles on 13 different drugs or substances (beer, cigarettes, wine, marijuana, hashish, etc.) (see Everitt, B. and Hothorn, T., *An Introduction to Applied Multivariate Analysis with `R`*, Springer, 2011).


```r
druguse
```

```
##                       cigarettes  beer  wine liquor cocaine tranquillizers drug store medication heroin
## cigarettes                 1.000 0.447 0.422  0.435   0.114          0.203                 0.091  0.082
## beer                       0.447 1.000 0.619  0.604   0.068          0.146                 0.103  0.063
## wine                       0.422 0.619 1.000  0.583   0.053          0.139                 0.110  0.066
## liquor                     0.435 0.604 0.583  1.000   0.115          0.258                 0.122  0.097
## cocaine                    0.114 0.068 0.053  0.115   1.000          0.349                 0.209  0.321
## tranquillizers             0.203 0.146 0.139  0.258   0.349          1.000                 0.221  0.355
## drug store medication      0.091 0.103 0.110  0.122   0.209          0.221                 1.000  0.201
## heroin                     0.082 0.063 0.066  0.097   0.321          0.355                 0.201  1.000
## marijuana                  0.513 0.445 0.365  0.482   0.186          0.315                 0.150  0.154
## hashish                    0.304 0.318 0.240  0.368   0.303          0.377                 0.163  0.219
## inhalants                  0.245 0.203 0.183  0.255   0.272          0.323                 0.310  0.288
## hallucinogenics            0.101 0.088 0.074  0.139   0.279          0.367                 0.232  0.320
## amphetamine                0.245 0.199 0.184  0.293   0.278          0.545                 0.232  0.314
##                       marijuana hashish inhalants hallucinogenics amphetamine
## cigarettes                0.513   0.304     0.245           0.101       0.245
## beer                      0.445   0.318     0.203           0.088       0.199
## wine                      0.365   0.240     0.183           0.074       0.184
## liquor                    0.482   0.368     0.255           0.139       0.293
## cocaine                   0.186   0.303     0.272           0.279       0.278
## tranquillizers            0.315   0.377     0.323           0.367       0.545
## drug store medication     0.150   0.163     0.310           0.232       0.232
## heroin                    0.154   0.219     0.288           0.320       0.314
## marijuana                 1.000   0.534     0.301           0.204       0.394
## hashish                   0.534   1.000     0.302           0.368       0.467
## inhalants                 0.301   0.302     1.000           0.340       0.392
## hallucinogenics           0.204   0.368     0.340           1.000       0.511
## amphetamine               0.394   0.467     0.392           0.511       1.000
```

For further details, see the help page of the data: `?druguse`


## `faithful`
The data, already included in the base `R` distribution, contains information on 272 eruptions for the Old Faithful geyser in Yellowstone National Park, Wyoming, USA: the eruption time and the waiting time to next eruption.


```r
str(faithful)
```

```
## 'data.frame':	272 obs. of  2 variables:
##  $ eruptions: num  3.6 1.8 3.33 2.28 4.53 ...
##  $ waiting  : num  79 54 74 62 85 55 88 85 51 85 ...
```

For further details, see the help page of the data: `?faithful`


## `forbes94`
The data deals with the compensation received in 1994 by the 800 most paid CEOs in US (This dataset comes from a ranking published by the Forbes newspaper in the same year).


```r
str(forbes94)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	800 obs. of  30 variables:
##  $ TotalComp     : int  600300 1487600 1508180 4069420 1088150 1099010 1652560 7285420 2271460 14899200 ...
##  $ WideIndustry  : Factor w/ 19 levels "Aerospacedefense",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Company       : Factor w/ 800 levels "20th Century Industr",..: 694 103 526 448 460 319 427 322 701 321 ...
##  $ CEO           : Factor w/ 796 levels "Dr. Andrew S Grove",..: 777 221 453 530 383 24 128 386 327 347 ...
##  $ CityofBirth   : Factor w/ 402 levels "","Aberdeen",..: 288 35 250 94 18 76 130 281 224 97 ...
##  $ StateofBirth  : Factor w/ 51 levels "","AK","AL","AR",..: 40 15 36 7 22 37 40 21 19 24 ...
##  $ Age           : int  52 62 56 58 56 60 62 58 59 64 ...
##  $ Undergrad     : Factor w/ 262 levels "","Albion C",..: 83 186 106 124 124 67 170 196 190 198 ...
##  $ UGDegree      : Factor w/ 25 levels "","AAS","AB",..: 13 23 13 17 13 3 19 13 13 13 ...
##  $ UGDate        : int  63 54 59 57 60 55 54 57 56 52 ...
##  $ AgeOfUnder    : int  21 22 21 21 22 21 22 21 21 22 ...
##  $ Graduate      : Factor w/ 129 levels "","American Grad S",..: 22 27 39 50 50 61 72 83 86 91 ...
##  $ GradDegree    : Factor w/ 20 levels "AM","EdD","JD",..: 12 8 12 15 12 8 16 20 12 12 ...
##  $ MBA           : int  0 1 0 0 0 1 0 0 0 0 ...
##  $ MasterPhd     : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ G_date        : int  67 58 61 59 62 57 55 60 58 53 ...
##  $ AgeOfGradu    : int  25 26 23 23 24 23 23 24 23 23 ...
##  $ YearsFirm     : int  8 36 19 17 32 10 39 34 4 13 ...
##  $ YearsCEO      : int  3 8 4 6 6 9 5 13 2 1 ...
##  $ Salary        : int  600000 796935 675000 830000 559477 650833 762500 1750000 725000 670000 ...
##  $ Bonus         : int  NA 624000 450000 800000 495100 330000 650000 2200000 950000 1350000 ...
##  $ Other         : int  300 66669 383184 1645320 33569 118175 240064 441046 596461 12879200 ...
##  $ StGains       : int  NA NA NA 794103 NA NA NA 2894380 NA NA ...
##  $ Compfor5Yrs   : int  2560750 7857540 7719720 12625100 4452230 4803290 6614390 31373600 6408090 NA ...
##  $ StockOwned    : num  0.004 0.004 0.576 0.108 3.326 ...
##  $ Sales         : int  2492 25438 5063 9436 14487 1905 13071 60562 9078 3187 ...
##  $ Profits       : num  72.8 1244 96 450.3 396 ...
##  $ ReturnOver5Yrs: int  -9 10 13 17 7 1 11 21 19 24 ...
##  $ Industry      : Factor w/ 71 levels "Aerospacedefense",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ IndustryCode  : num  11 11 11 11 11 11 11 11 11 11 ...
```

For further details, see the help page of the data: `?forbes94`


## `german`
This dataset deals with a sample of 1,000 customers which apply for a credit card. Some have defaulted (Bad class) and other not (Good) on the credit card. 20 further characteristics about them or their credit card have been measured. 


```r
str(german)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	1000 obs. of  21 variables:
##  $ StatusAccount         : Factor w/ 4 levels "lt.0","ge.0.lt200",..: 1 2 4 1 1 4 4 2 4 2 ...
##  $ Duration              : int  6 48 12 42 24 36 24 36 12 30 ...
##  $ CreditHistory         : Factor w/ 5 levels "no credits","all credits this bank paid",..: 5 3 5 3 4 3 3 3 3 5 ...
##  $ Purpose               : Factor w/ 10 levels "car (new)","car (used)",..: 5 5 8 4 1 8 4 2 5 1 ...
##  $ CreditAmount          : int  1169 5951 2096 7882 4870 9055 2835 6948 3059 5234 ...
##  $ SavingsAccountBonds   : Factor w/ 5 levels "lt.100","ge.100.lt.500",..: 5 1 1 1 1 5 3 1 4 1 ...
##  $ EmployedSince         : Factor w/ 5 levels "unemployed","lt.1y",..: 5 3 4 4 3 3 5 3 4 1 ...
##  $ RatePercIncome        : int  4 2 2 2 3 2 3 2 2 4 ...
##  $ StatusAndSex          : Factor w/ 5 levels "maleDivorced",..: 3 2 3 3 3 3 3 3 1 4 ...
##  $ OtherBebtorsGarants   : Factor w/ 3 levels "none","co-applicant",..: 1 1 1 3 1 1 1 1 1 1 ...
##  $ ResidenceSince        : int  4 2 3 4 4 4 4 2 4 2 ...
##  $ Property              : Factor w/ 4 levels "real estate",..: 1 1 1 2 4 4 2 3 1 3 ...
##  $ AgeYears              : int  67 22 49 45 53 35 53 35 61 28 ...
##  $ OtherInstallPlans     : Factor w/ 3 levels "bank","stores",..: 3 3 3 3 3 3 3 3 3 3 ...
##  $ Housing               : Factor w/ 3 levels "rent","own","for free": 2 2 2 3 3 3 2 1 2 2 ...
##  $ NumberOfCredits       : int  2 1 1 1 2 1 1 1 1 2 ...
##  $ Job                   : Factor w/ 4 levels "unemployed/unskilled-non resident",..: 3 3 2 3 3 2 3 4 2 4 ...
##  $ NumberPeopleMaintained: int  1 1 2 2 2 2 1 1 1 1 ...
##  $ Telephone             : Factor w/ 2 levels "none","yes": 2 1 1 1 1 2 1 2 1 1 ...
##  $ ForeignWorker         : Factor w/ 2 levels "yes","no": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Class                 : Factor w/ 2 levels "Good","Bad": 1 2 1 1 2 1 1 1 1 2 ...
```

For further details, see the help page of the data: `?german`


## `iris`
The data, already included in the base `R` distribution, contains the measurements in centimeters of the variables sepal length and width and petal length and width, respectively, for 50 flowers from each of 3 species of iris. 


```r
str(iris)
```

```
## 'data.frame':	150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
```

For further details, see the help page of the data: `?iris`


## `kyphosis`
This dataset, included in the `R` package `rpart`, has 81 rows representing data on 81 children who have had corrective spinal surgery. Age, number of vertebrae involved and the first vertebra operated on were detected on the children, besides the indication of presence or absence of kyphosis (a type of deformation).


```r
str(kyphosis)
```

```
## 'data.frame':	81 obs. of  4 variables:
##  $ Kyphosis: Factor w/ 2 levels "absent","present": 1 1 2 1 1 1 1 1 1 2 ...
##  $ Age     : int  71 158 128 2 1 1 61 37 113 59 ...
##  $ Number  : int  3 3 4 5 4 2 2 3 2 6 ...
##  $ Start   : int  5 14 5 1 15 16 17 16 16 12 ...
```

For further details, see the help page of the data: `?rpart::kyphosis`


## `life`
The data contains life expectations at birth, 25, 50 and 75 years for men and women in 31 Countries or regions (Everitt, B. and Hothorn, T., *An Introduction to Applied Multivariate Analysis with `R`*, Springer, 2011).


```r
str(life)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	31 obs. of  9 variables:
##  $ country: chr  "Algeria" "Cameroon" "Madagascar" "Mauritius" ...
##  $ m0     : num  63 34 38 59 56 62 50 65 56 69 ...
##  $ m25    : num  51 29 30 42 38 44 39 44 46 47 ...
##  $ m50    : num  30 13 17 20 18 24 20 22 24 24 ...
##  $ m75    : num  13 5 7 6 7 7 7 7 11 8 ...
##  $ w0     : num  67 38 38 64 62 69 55 72 63 75 ...
##  $ w25    : num  54 32 34 46 46 50 43 50 54 53 ...
##  $ w50    : num  34 17 20 25 25 28 23 27 33 29 ...
##  $ w75    : num  15 6 7 8 10 14 8 9 19 10 ...
```

For further details, see the help page of the data: `?life`


## `mds`
This fictional data contains 10 observations on which 5 numerical variables are measured.


```r
str(mds)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	10 obs. of  5 variables:
##  $ V1: num  3 5 6 1 4 2 0 0 7 2
##  $ V2: num  4 1 2 1 7 2 4 6 6 1
##  $ V3: num  4 1 0 1 3 5 1 4 5 4
##  $ V4: num  6 7 2 0 6 1 1 3 1 3
##  $ V5: num  1 3 6 3 2 0 1 5 4 1
```

For further details, see the help page of the data: `?mds`


## `Smarket`
This dataset, included in the `R` package `ISLR`, deals with percentage returns for the S&P 500 stock index over 1250 days, from the beginning of 2001 until the end of 2005 (see James, G., Witten, D., Hastie, T., and Tibshirani, R., *An Introduction to Statistical Learning with applications in `R`*, Springer, 2013). For each date, the percentage returns for each of the five previous trading days (Lag1 through Lag5), the number of shares traded on the previous day (Volume, in billions), the percentage return on the date in question (Today) and whether the market was up or down on this date (Direction) have been recorded.


```r
str(Smarket)
```

```
## 'data.frame':	1250 obs. of  9 variables:
##  $ Year     : num  2001 2001 2001 2001 2001 ...
##  $ Lag1     : num  0.381 0.959 1.032 -0.623 0.614 ...
##  $ Lag2     : num  -0.192 0.381 0.959 1.032 -0.623 ...
##  $ Lag3     : num  -2.624 -0.192 0.381 0.959 1.032 ...
##  $ Lag4     : num  -1.055 -2.624 -0.192 0.381 0.959 ...
##  $ Lag5     : num  5.01 -1.055 -2.624 -0.192 0.381 ...
##  $ Volume   : num  1.19 1.3 1.41 1.28 1.21 ...
##  $ Today    : num  0.959 1.032 -0.623 0.614 0.213 ...
##  $ Direction: Factor w/ 2 levels "Down","Up": 2 2 1 2 2 2 1 2 2 2 ...
```

For further details, see the help page of the data: `?ISLR::Smarket`


## `skulls`
This dataset, included in the `R` package `HSAUR2`, deals with 150 male Egyptian skulls from five epochs classified by 4 measurements (see Everitt, B. and Hothorn, T., *An Introduction to Applied Multivariate Analysis with `R`*, Springer, 2011).


```r
str(skulls)
```

```
## 'data.frame':	150 obs. of  5 variables:
##  $ epoch: Ord.factor w/ 5 levels "c4000BC"<"c3300BC"<..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ mb   : num  131 125 131 119 136 138 139 125 131 134 ...
##  $ bh   : num  138 131 132 132 143 137 130 136 134 134 ...
##  $ bl   : num  89 92 99 96 100 89 108 93 102 99 ...
##  $ nh   : num  49 48 50 44 54 56 48 48 51 51 ...
```

For further details, see the help page of the data: `?HSAUR2::skulls`


## `uscompanies`
This dataset deals with 79 U.S. companies (see Härdle and Simar, *Applied Multivariate Statistical Analysis*, 3rd ed., Springer, 2012) classified by 6 numerical characteristics (assets, sales, etc.) and one categorical characteristic (industry); indshort is a shortening for industry.


```r
str(uscompanies)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	79 obs. of  9 variables:
##  $ company  : Factor w/ 79 levels "AHRobins","AirProducts",..: 11 20 4 12 15 17 18 31 42 44 ...
##  $ assets   : int  19788 5074 13621 1117 1633 5651 5835 3494 1654 1679 ...
##  $ sales    : int  9084 2557 4848 1038 701 1254 4053 1653 451 1354 ...
##  $ value    : int  10636 1892 4572 478 679 2002 1601 1442 779 687 ...
##  $ profits  : num  1092.9 239.9 485 59.7 74.3 ...
##  $ cashflow : num  2576.8 578.3 898.9 91.7 135.9 ...
##  $ employees: num  79.4 21.9 23.4 3.8 2.8 6.2 10.8 6.4 1.6 4.6 ...
##  $ industry : Factor w/ 9 levels "Communication",..: 1 1 2 2 2 2 2 2 2 2 ...
##  $ indshort : Factor w/ 6 levels "H","E","F","M",..: 1 1 2 2 2 2 2 2 2 2 ...
```

For further details, see the help page of the data: `?uscompanies`


## `uscrime`
The data deals with crime rates (number of crimes per 100,000 residents) in the 50 U.S.; the dataset includes also land and population (in 1985) of the 50 U.S., which are classified by the following seven categories: murder, rape, robbery, assault, burglary, larceny and auto-theft (from Härdle, W. K. and Simar, L., *Applied Multivariate Statistical Analysis*, 3rd edition, Springer, 2012).


```r
str(uscrime)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	50 obs. of  12 variables:
##  $ state   : chr  "ME" "NH" "VT" "MA" ...
##  $ land    : int  33265 9279 9614 8284 1212 5018 49108 7787 45308 41330 ...
##  $ popu1985: int  1164 998 535 5822 968 3174 17783 7562 11853 10744 ...
##  $ murd    : num  1.5 2 1.3 3.5 3.2 3.5 7.9 5.7 5.3 6.6 ...
##  $ rape    : num  7 6 10.3 12 3.6 9.1 15.5 12.9 11.3 16 ...
##  $ robb    : num  12.6 12.1 7.6 99.5 78.3 ...
##  $ assa    : int  62 36 55 88 120 87 209 90 90 116 ...
##  $ burg    : int  562 566 731 1134 1019 1084 1414 1041 594 854 ...
##  $ larc    : int  1055 929 969 1531 2186 1751 2025 1689 1001 1944 ...
##  $ auto    : int  146 172 124 878 859 484 682 557 340 493 ...
##  $ reg     : int  1 1 1 1 1 1 1 1 1 2 ...
##  $ div     : int  1 1 1 1 1 1 2 2 2 3 ...
```

For further details, see the help page of the data: `?uscrime`


## `utilities`
This dataset deals with 22 U.S. companies classified by 8 numerical characteristics (coverage, return, cost, etc.).


```r
str(utilities)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	22 obs. of  10 variables:
##  $ coverage  : num  1.06 0.89 1.43 1.02 1.49 1.32 1.22 1.1 1.34 1.12 ...
##  $ return    : num  9.2 10.3 15.4 11.2 8.8 13.5 12.2 9.2 13 12.4 ...
##  $ cost      : int  151 202 113 168 192 111 175 245 168 197 ...
##  $ load      : num  54.4 57.9 53 56 51.2 60 67.6 57 60.4 53 ...
##  $ peak      : num  1.6 2.2 3.4 0.3 1 -2.2 2.2 3.3 7.2 2.7 ...
##  $ sales     : int  9077 5088 9212 6423 3300 11127 7642 13082 8406 6455 ...
##  $ nuclear   : num  0 25.3 0 34.3 15.6 22.5 0 0 0 39.2 ...
##  $ fuel      : num  0.628 1.555 1.058 0.7 2.044 ...
##  $ company   : chr  "Arizona Public Service" "Boston Edison Co." "Central Louisiana Electric Co." "Commonwealth Edison Co." ...
##  $ comp_short: chr  "Arizona" "Boston" "Central" "Common" ...
##  - attr(*, "datalabel")= chr "Data on 22 U.S. public utility companies for the year 1975"
##  - attr(*, "time.stamp")= chr " 6 Nov 2011 12:51"
##  - attr(*, "formats")= chr  "%9.0g" "%9.0g" "%9.0g" "%9.0g" ...
##  - attr(*, "types")= int  255 255 252 255 255 252 255 255 30 8
##  - attr(*, "val.labels")= chr  "" "" "" "" ...
##  - attr(*, "var.labels")= chr  "Fixed-charge coverage ratio (income/debt)" "Rate of return on capital" "Cost per kW capacity in place" "Annual load factor" ...
##  - attr(*, "expansion.fields")=List of 2
##   ..$ : chr  "_dta" "note1" "Taken from Johnson, R. A. and Wichern, D. W., Applied Multivariate Statistical Analysis, 6th edition, Prentice Hall"
##   ..$ : chr  "_dta" "note0" "1"
##  - attr(*, "version")= int 12
```

For further details, see the help page of the data: `?utilities`


## `volcano3d`
The data, derived from the `volcano` dataset included in the base `R` distribution, gives the topographic information for Maunga Whau, one of about 50 volcanos in the Auckland volcanic field, on a 10m by 10m grid. 


```r
str(volcano3d)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	5307 obs. of  3 variables:
##  $ x: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ y: int  1 1 1 1 1 1 1 1 1 1 ...
##  $ z: num  100 101 102 103 104 105 105 106 107 108 ...
```

For further details, see the help page of the data: `?volcano3d`


## `wea`
Weather daily data (temperature, rain, wind, etc.) in Canberra, Australia, from 2007-11-01 to 2008-10-31.


```r
str(wea)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	366 obs. of  24 variables:
##  $ Date         : Date, format: "2007-11-01" "2007-11-02" "2007-11-03" ...
##  $ Location     : Factor w/ 49 levels "Adelaide","Albany",..: 10 10 10 10 10 10 10 10 10 10 ...
##  $ MinTemp      : num  8 14 13.7 13.3 7.6 6.2 6.1 8.3 8.8 8.4 ...
##  $ MaxTemp      : num  24.3 26.9 23.4 15.5 16.1 16.9 18.2 17 19.5 22.8 ...
##  $ Rainfall     : num  0 3.6 3.6 39.8 2.8 0 0.2 0 0 16.2 ...
##  $ Evaporation  : num  3.4 4.4 5.8 7.2 5.6 5.8 4.2 5.6 4 5.4 ...
##  $ Sunshine     : num  6.3 9.7 3.3 9.1 10.6 8.2 8.4 4.6 4.1 7.7 ...
##  $ WindGustDir  : Ord.factor w/ 16 levels "N"<"NNE"<"NE"<..: 15 4 15 15 8 7 7 5 9 5 ...
##  $ WindGustSpeed: num  30 39 85 54 50 44 43 41 48 31 ...
##  $ WindDir9am   : Ord.factor w/ 16 levels "N"<"NNE"<"NE"<..: 11 5 1 14 8 7 7 7 5 9 ...
##  $ WindDir3pm   : Ord.factor w/ 16 levels "N"<"NNE"<"NE"<..: 15 13 2 13 6 5 6 5 4 6 ...
##  $ WindSpeed9am : num  6 4 6 30 20 20 19 11 19 7 ...
##  $ WindSpeed3pm : num  20 17 6 24 28 24 26 24 17 6 ...
##  $ Humidity9am  : int  68 80 82 62 68 70 63 65 70 82 ...
##  $ Humidity3pm  : int  29 36 69 56 49 57 47 57 48 32 ...
##  $ Pressure9am  : num  1020 1012 1010 1006 1018 ...
##  $ Pressure3pm  : num  1015 1008 1007 1007 1018 ...
##  $ Cloud9am     : int  7 5 8 2 7 7 4 6 7 7 ...
##  $ Cloud3pm     : int  7 3 7 7 7 5 6 7 7 1 ...
##  $ Temp9am      : num  14.4 17.5 15.4 13.5 11.1 10.9 12.4 12.1 14.1 13.3 ...
##  $ Temp3pm      : num  23.6 25.7 20.2 14.1 15.4 14.8 17.3 15.5 18.9 21.7 ...
##  $ RainToday    : Factor w/ 2 levels "No","Yes": 1 2 2 2 2 1 1 1 1 2 ...
##  $ RISK_MM      : num  3.6 3.6 39.8 2.8 0 0.2 0 0 16.2 0 ...
##  $ RainTomorrow : Factor w/ 2 levels "No","Yes": 2 2 2 2 1 1 1 1 2 1 ...
```

For further details, see the help page of the data: `?wea`


## `wines`
The data, derived from the dataset with the same name included in the `R` package `kohonen`, contains information on a set of 177 Italian wine samples from three different grape cultivars; 13 variables have been measured (alcohol, malic acid, tc.). 


```r
str(wines)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	177 obs. of  15 variables:
##  $ alcohol          : num  13.2 13.2 14.4 13.2 14.2 ...
##  $ malic.acid       : num  1.78 2.36 1.95 2.59 1.76 1.87 2.15 1.64 1.35 2.16 ...
##  $ ash              : num  2.14 2.67 2.5 2.87 2.45 2.45 2.61 2.17 2.27 2.3 ...
##  $ ash.alkalinity   : num  11.2 18.6 16.8 21 15.2 14.6 17.6 14 16 18 ...
##  $ magnesium        : num  100 101 113 118 112 96 121 97 98 105 ...
##  $ tot..phenols     : num  2.65 2.8 3.85 2.8 3.27 2.5 2.6 2.8 2.98 2.95 ...
##  $ flavonoids       : num  2.76 3.24 3.49 2.69 3.39 2.52 2.51 2.98 3.15 3.32 ...
##  $ non.flav..phenols: num  0.26 0.3 0.24 0.39 0.34 0.3 0.31 0.29 0.22 0.22 ...
##  $ proanth          : num  1.28 2.81 2.18 1.82 1.97 1.98 1.25 1.98 1.85 2.38 ...
##  $ col..int.        : num  4.38 5.68 7.8 4.32 6.75 5.25 5.05 5.2 7.22 5.75 ...
##  $ col..hue         : num  1.05 1.03 0.86 1.04 1.05 1.02 1.06 1.08 1.01 1.25 ...
##  $ OD.ratio         : num  3.4 3.17 3.45 2.93 2.85 3.58 3.58 2.85 3.55 3.17 ...
##  $ proline          : num  1050 1185 1480 735 1450 ...
##  $ vintages         : Factor w/ 3 levels "Barbera","Barolo",..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ wine.classes     : num  1 1 1 1 1 1 1 1 1 1 ...
```

For further details, see the help page of the data: `?wines`


## `wwiileaders`
The data contains a distance matrix among 12 country leaders during II World War, which is based on the judgments of the dissimilarities in ideology. The subjects made judgments on a nine-point scale, with the extreme points of the scale, 1 and 9, being described as indicating “very similar” and “very dissimilar”, respectively (see Everitt, B. and Hothorn, T., *An Introduction to Applied Multivariate Analysis with `R`*, Springer, 2011).


```r
wwiileaders
```

```
##              Hitler Mussolini Churchill Eisenhower Stalin Attlee Franco De Gaulle Mao Tse-Tung Truman
## Mussolini         3                                                                                  
## Churchill         4         6                                                                        
## Eisenhower        7         8         4                                                              
## Stalin            3         5         6          8                                                   
## Attlee            8         9         3          9      8                                            
## Franco            3         2         5          7      6      7                                     
## De Gaulle         4         4         3          5      6      5      4                              
## Mao Tse-Tung      8         9         8          9      6      9      8         7                    
## Truman            9         9         5          4      7      8      8         4            4       
## Chamberlin        4         5         5          4      7      2      2         5            9      5
## Tito              7         8         2          4      7      8      3         2            4      5
##              Chamberlin
## Mussolini              
## Churchill              
## Eisenhower             
## Stalin                 
## Attlee                 
## Franco                 
## De Gaulle              
## Mao Tse-Tung           
## Truman                 
## Chamberlin             
## Tito                  7
```

For further details, see the help page of the data: `?wwiileaders`


